src/Controller/TasksController.php

@maurobonfietti requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/maurobonfietti/api-rest-slimphp/

Scrutinizer Auto-Fixes

---

app/data/database.sql
app/routes.php
composer.json
composer.lock
phpunit.xml
src/Controller/DefaultController.php
src/Controller/User/GetOneUser.php
src/Middlewares/AuthMiddleware.php
src/Repository/UserRepository.php
src/Service/UserService.php
tests/api/BaseTestCase.php
tests/api/DefaultTest.php
tests/api/UserTest.php

- Add new login endpoint + PHPUnit test.
- Add new password field in user table.
- Encrypt pass with sha512 hash.
- Use package firebase/php-jwt.
- Add Authorization JWT Token Middleware.
- Test Authorization JWT Token in Get One User endpoint.
- Making that manage notes as public, and tasks belong to an user.
- Add color in PHPUnit tests.
- Minor changes in PHPUnit tests.
- Another minor changes.
- Do composer update.

New Branch with Auth Login JWT

---

app/data/database.sql
app/routes.php
src/Handlers/ApiError.php
src/Repository/TaskRepository.php
src/Service/TaskService.php
tests/api/DefaultTest.php

- Now each task belong to an user.
- Use POST HTTP Method in login endpoint.
- New PHPUnit Test when Login Failed.
- Show exception classname when you throw a exception.

A task belong to an user.

---

app/routes.php
app/services.php
src/Controller/DefaultController.php
src/Controller/User/LoginUser.php
src/Handler/ApiError.php
src/Middleware/AuthMiddleware.php
src/Repository/UserRepository.php
src/Service/UserService.php
tests/api/AuthLoginTest.php
tests/api/DefaultTest.php
tests/api/UserTest.php

- Move User Login functionality.
- Rename namespaces for Handler and Middleware.
- Minor changes in PHPUnit Tests.

Minor changes

---

tests/integration/UserTest.php
tests/unit/Service/UserServiceTest.php

- Add unit test that try to create an user without a name, and expected an UserException.
- Fix integration test to increase code coverage.
- Minor improve in unit tests.

Adding PHPUnit Tests

---

database/database.sql
src/App/routes.php
src/Controller/DefaultController.php
src/Controller/Task/DeleteTask.php
src/Controller/Task/GetAllTasks.php
src/Controller/Task/GetOneTask.php
src/Controller/Task/SearchTasks.php
src/Repository/TaskRepository.php
src/Service/TaskService.php

- Manage tasks that belong to his authorized user.
- Validate that each tasks belong to his own user.
- Fix integration tests.

JWT Part 2 :-)

---

src/App/routes.php
src/Controller/User/BaseUser.php
src/Controller/User/DeleteUser.php
src/Controller/User/GetOneUser.php
src/Controller/User/UpdateUser.php
tests/integration/UserTest.php

- Use JWT Auth Bearer when manage users.
- Validate that each user can edit/delete only his own user.
- Fix integration tests.

Auth JWT Token Part 3 :-P

---

README.md
README_SPANISH.md
src/Middleware/AuthMiddleware.php
src/Repository/UserRepository.php
tests/integration/UserTest.php

- Do not show user password hash.
- Fix Integration Tests.
- Fix PHP Doc Block.
- Minor fixes.
- Minor changes. 

Improvements

---

README.md
README_SPANISH.md
database/database.sql
src/Controller/DefaultController.php
src/Service/BaseService.php

- Update validation for the name of the note.
- Update database user's password hashes.
- Release new version :-)

Develop Version: 0.20.1

---

src/App/Dependencies.php
src/Controller/DefaultController.php
tests/integration/NoteTest.php

- Set attribute PDO Emulate Prepares in false.
- Update integration test.

Version 0.22.1

---

src/Controller/DefaultController.php
src/Repository/TaskRepository.php
src/Service/TaskService.php

- Show tasks count in status endpoint.

Version 0.22.2

---

README.md
README_SPANISH.md
src/Controller/DefaultController.php
src/Controller/Task/SearchTasks.php
src/Repository/TaskRepository.php
src/Service/TaskService.php
tests/integration/TaskTest.php

- Allow filter tasks by status.
- Minor changes in search tasks endpoint.
- Add integration tests for search tasks endpoint.
- Preparing for connect this API with a WebApp in Angular.js

Version 0.24.0

---

src/App/Dependencies.php
src/App/Services.php
src/Controller/BaseController.php
src/Controller/DefaultController.php
src/Controller/Note/BaseNote.php
src/Controller/Note/CreateNote.php
src/Controller/Note/DeleteNote.php
src/Controller/Note/GetOneNote.php
src/Controller/Note/UpdateNote.php
src/Controller/User/BaseUser.php
src/Controller/User/CreateUser.php
src/Controller/User/DeleteUser.php
src/Controller/User/GetOneUser.php
src/Controller/User/UpdateUser.php
src/Service/BaseService.php
src/Service/NoteService.php
src/Service/RedisService.php
src/Service/TaskService.php
src/Service/UserService.php
tests/unit/Service/UserServiceTest.php

- Add New Redis Service.
- Use Redis Service when manage Notes, Users and Tasks.
- Minor changes.
- Cleaning.

Add and Use Redis Service

---

.env.example
.travis.yml
README.md
README_SPANISH.md
src/App/Settings.php
src/Controller/BaseController.php
src/Controller/DefaultController.php
src/Controller/Note/BaseNote.php
src/Controller/Task/BaseTask.php
src/Controller/User/BaseUser.php
src/Middleware/AuthMiddleware.php
src/Repository/BaseRepository.php
src/Service/BaseService.php
src/Service/NoteService.php
src/Service/RedisService.php
src/Service/TaskService.php
src/Service/UserService.php

- Changes and improvements in Redis Service.
- Redis service made more simple.
- Remove PHP Doc Blocks unnecessary.
- Some minor changes.
- Cleaning.

Release Version 0.27.0

---

composer.json
composer.lock
src/Controller/DefaultController.php

- Update slim version to 3.12.2.

Update slim version to 3.12.2

---

Makefile
README.md
README_SPANISH.md
docker-compose.yml
docker/php7/Dockerfile
src/Controller/DefaultController.php

Update docker files configuration:
- Change webserver port to 8081.
- Enable xdebug to check code coverage.
- Add option: 'make coverage', to run unit tests and get code coverage.

Release Version 0.29.0

---

README.md
README_SPANISH.md
src/Controller/DefaultController.php
src/Middleware/AuthMiddleware.php
tests/integration/TaskTest.php

- Simplify Auth Middleware and checkToken method.
- Update PHP Unit Tests.

Release Version 0.30.0

---

src/Controller/BaseController.php
src/Controller/DefaultController.php
src/Controller/Note/CreateNote.php
src/Controller/Note/DeleteNote.php
src/Controller/Note/GetAllNotes.php
src/Controller/Note/GetOneNote.php
src/Controller/Note/SearchNotes.php
src/Controller/Note/UpdateNote.php
src/Controller/Task/CreateTask.php
src/Controller/Task/DeleteTask.php
src/Controller/Task/GetAllTasks.php
src/Controller/Task/GetOneTask.php
src/Controller/Task/SearchTasks.php
src/Controller/Task/UpdateTask.php
src/Controller/User/BaseUser.php
src/Controller/User/CreateUser.php
src/Controller/User/DeleteUser.php
src/Controller/User/GetAllUsers.php
src/Controller/User/GetOneUser.php
src/Controller/User/LoginUser.php
src/Controller/User/SearchUsers.php
src/Controller/User/UpdateUser.php

- Minor changes when use $args request params.
- Changes when use the function jsonResponse().
- Remove old function setParams().

Version 0.32.0

---

README.md
README_SPANISH.md
src/Controller/DefaultController.php
src/Middleware/AuthMiddleware.php
src/Repository/TaskRepository.php
src/Service/NoteService.php
src/Service/TaskService.php
src/Service/UserService.php
tests/integration/NoteTest.php
tests/integration/TaskTest.php
tests/integration/UserTest.php

- Remove some code smells.
- Update PHPUnit integration tests.

Version 0.33.0

---

composer.json
composer.lock
src/Handler/ApiError.php

#57 
- Sort packages and normalize composer.json file.
- New command available: 'composer coverage', to get the code coverage of the app.
- In case of any error, throw an exception with a new header content type: 'application/problem+json'.
- Minor changes in ApiError.

Version 0.34.0

---

src/App/Dependencies.php
src/App/Repositories.php
src/App/Routes.php
src/App/Services.php
src/Controller/DefaultController.php
src/Controller/User/Base.php
src/Controller/User/Delete.php
src/Controller/User/Update.php
src/Handler/ApiError.php
src/Middleware/Auth.php
src/Repository/NoteRepository.php
src/Repository/TaskRepository.php
src/Repository/UserRepository.php
src/Service/Note/BaseNoteService.php
src/Service/RedisService.php
src/Service/TaskService.php
src/Service/UserService.php

Fix some issues detected with PHP Insights.

Version 0.50.0

---

composer.json
src/App/Services.php
src/Controller/DefaultController.php
src/Controller/Task/Base.php
src/Controller/User/Base.php
src/Service/BaseService.php
src/Service/Task/Base.php
src/Service/Task/TaskService.php
src/Service/User/Base.php
src/Service/User/UserService.php
tests/unit/Service/UserServiceTest.php

- Show message after create a project with composer.
- Refactor User Service.
- Refactor Task Service.
- Refactor Task Service.
- Minor changes.

Version 0.53.0

---

src/App/Routes.php
src/Controller/BaseController.php
src/Controller/DefaultController.php
src/Middleware/Auth.php
src/Repository/BaseRepository.php
src/Repository/NoteRepository.php
src/Repository/TaskRepository.php
src/Repository/UserRepository.php
src/Service/Note/Base.php
src/Service/Note/NoteService.php
src/Service/RedisService.php
src/Service/Task/Base.php
src/Service/Task/TaskService.php
src/Service/User/Base.php
src/Service/User/UserService.php

- Some minor changes in services.
- Fix several issues detected with PHP Insights.
- Update Message Post Create Project Command.

Version 0.55.0

---

composer.json
extras/bin/post-create-project-command.php
src/Controller/DefaultController.php

- Set timeout when run commands like composer start.
- Move and update message post create project command.

Version 0.56.0

---

README.md
database/database.sql
src/Controller/DefaultController.php

- Update database: Add foreign key for task user.
- Remove fields for created_at and update_at.

Version 0.57.0

---

README.md
README_SPANISH.md
composer.json
composer.lock
src/Controller/DefaultController.php

- Add minimum-stability and prefer-stable in composer.json
- composer require pestphp/pest --dev

Version 0.58.0

---

README.md
README_SPANISH.md
composer.json
composer.lock
src/App/Dependencies.php
src/App/Repositories.php
src/App/Services.php
src/Service/Note/NoteService.php
src/Service/Task/TaskService.php

- composer require rector/rector --dev
- vendor/bin/rector process src --set php74
- php-cs-fixer fix src

Version 0.59.0

---

extras/bin/post-create-project-command.php
extras/bin/restart-db.php
src/App/Dependencies.php
src/App/Repositories.php
src/App/Routes.php
src/Controller/DefaultController.php
src/Middleware/Base.php

Version 0.60.0

---

src/Controller/DefaultController.php

- Release version 1.0.0 for reaching 100 stars in this repo.
**Thanks all of you!**

Version: 1.0.0

---

.scrutinizer.yml
Makefile
README.md
README_SPANISH.md
src/App/Dependencies.php
src/App/Services.php
src/Controller/DefaultController.php

Version 1.2.0

---

src/App/Services.php
src/Controller/DefaultController.php
src/Handler/ApiError.php
src/Middleware/Base.php
src/Service/Note/Base.php
src/Service/RedisService.php
src/Service/Task/Base.php
src/Service/Task/TaskService.php
src/Service/User/Base.php
src/Service/User/UserService.php

- Added some specified parameter type hint.
- Added some specified return type hint.
- Others minor changes.

Version 1.4.0

---

extras/bin/post-create-project-command.php
extras/bin/restart-db.php
src/App/App.php
src/App/Dependencies.php
src/App/Middleware.php
src/App/Repositories.php
src/App/Services.php
src/App/Settings.php
src/Controller/DefaultController.php
src/Controller/Note/Create.php
src/Controller/Note/Update.php
src/Controller/Task/Create.php
src/Controller/Task/Update.php
src/Controller/User/Create.php
src/Controller/User/Login.php
src/Controller/User/Update.php
src/Handler/ApiError.php
src/Repository/TaskRepository.php
src/Service/Note/NoteService.php
src/Service/Task/Base.php
src/Service/Task/TaskService.php
src/Service/User/Base.php
src/Service/User/UserService.php
tests/integration/BaseTestCase.php

- Move environment variables for database connection settings.
- Set CorsSlim() in App.php & Remove Middleware.php
- Expect $request->getParsedBody() as array.
- Added specified parameter type hint.
- Added specified return type hint.
- Changes when app define containers.
- Fixed create/restart database script.
- Updated BaseTestCase.
- Refactor: Create user.
- Refactor: Update task.

Version 1.5.0

---

.travis.yml
README.md
README_SPANISH.md
src/App/Dependencies.php
src/Controller/BaseController.php
src/Controller/DefaultController.php
src/Repository/BaseRepository.php
src/Service/Note/Base.php
src/Service/Note/NoteService.php
src/Service/RedisService.php
src/Service/Task/Base.php
src/Service/Task/TaskService.php
src/Service/User/Base.php
tests/integration/BaseTestCase.php

- Minor changes to get code compatibility with PHP 7.3 and 7.4

Version 1.6.0

---

README.md
README_SPANISH.md
composer.json
composer.lock
src/App/Dependencies.php
src/App/Repositories.php
src/App/Routes.php
src/App/Services.php
src/Controller/DefaultController.php
src/Repository/NoteRepository.php
src/Repository/TaskRepository.php
src/Repository/UserRepository.php
src/Service/Note/Base.php
src/Service/Task/Base.php
src/Service/User/Base.php

- Require PHP >= 7.3
- Run: composer update.
- Minor changes in Routes.
- Minor changes to avoid lines that exceeds 80 characters.

Version 1.7.0

---

README.md
README_SPANISH.md
src/App/Routes.php
src/Controller/BaseController.php
src/Controller/DefaultController.php
src/Controller/Note/Base.php
src/Controller/Task/Base.php
src/Controller/User/Base.php
src/Service/Note/Base.php
src/Service/Task/Base.php
src/Service/User/Base.php
tests/integration/BaseTestCase.php
tests/integration/DefaultTest.php
tests/integration/NoteTest.php
tests/integration/TaskTest.php
tests/integration/UserTest.php
tests/unit/Service/UserServiceTest.php

- Change some routes.
- Move construct container to Base Controller.
- Allow name for Task/User/Note with at least 1 character.

Version 1.8.0

---

src/App/Services.php
src/Controller/DefaultController.php
src/Controller/Note/Base.php
src/Controller/Note/Create.php
src/Controller/Note/Delete.php
src/Controller/Note/GetAll.php
src/Controller/Note/GetOne.php
src/Controller/Note/Search.php
src/Controller/Note/Update.php
src/Service/Note/Create.php
src/Service/Note/Delete.php
src/Service/Note/Find.php
src/Service/Note/Get.php
src/Service/Note/NoteService.php
src/Service/Note/Update.php
tests/integration/NoteTest.php

- Refactor: Note Service.
- Minor changes.

Version 1.10.0

---

README.md
README_SPANISH.md
composer.json
database/database.sql
src/Controller/BaseController.php
src/Controller/DefaultController.php
src/Controller/Note/GetAll.php
src/Repository/BaseRepository.php
src/Repository/NoteRepository.php
src/Service/Note/Base.php
src/Service/Note/Find.php
tests/integration/NoteTest.php

- Add possibility of pagination for the endpoint: get all notes.
- Added some defaults notes/quotes examples from: brainyquote.com.
- Add PHPUnit tests.
- Replace 0.0.0.0:8080 for localhost:8080

Version 1.11.0

---

composer.json
composer.lock
src/App/App.php
src/Controller/DefaultController.php
tests/integration/BaseTestCase.php

- Create FUNDING.yml
- Set config platform PHP 7.3
- Updating vlucas/phpdotenv (v2.6.6 => v5.1.0).
- Reading env var with new Dotenv version.

Version 1.12.0

---

.travis.yml
extras/bin/restart-db.php
src/App/Dependencies.php
src/App/Settings.php
src/Controller/BaseController.php
src/Controller/DefaultController.php
src/Middleware/Base.php
src/Service/BaseService.php
src/Service/User/UserService.php

- Replace the use of getenv() for $_SERVER[].
- Set environment variables in Settings.

Version 1.14.0

---

src/Controller/DefaultController.php
src/Service/User/Base.php

- Allow some special characters when create/edit username.

Version 1.15.0

---

src/Controller/BaseController.php
src/Controller/DefaultController.php
src/Controller/Note/GetAll.php
src/Repository/BaseRepository.php
src/Repository/NoteRepository.php
src/Service/BaseService.php
src/Service/Note/Find.php
tests/integration/NoteTest.php

- Endpoint that allow search notes by name and description.

Version 1.16.0

---

README.md
README_SPANISH.md
composer.lock
phpunit.xml
src/Controller/DefaultController.php
src/Controller/User/GetAll.php
src/Repository/UserRepository.php
src/Service/User/UserService.php
tests/integration/UserTest.php

- Allow search and get all users with pagination.
- Added PHPUnit test.
- phpunit --migrate-configuration

Version 1.18.0

---

README.md
README_SPANISH.md
composer.json
composer.lock
psalm.xml
src/Controller/DefaultController.php
src/Controller/Task/Delete.php
src/Controller/User/Delete.php
src/Repository/BaseRepository.php
src/Repository/NoteRepository.php
src/Repository/UserRepository.php
src/Service/Note/Find.php
src/Service/User/UserService.php

- composer update
- composer require --dev vimeo/psalm
- Update some param types and return types.
- Some minor changes detected with psalm.

Version 1.19.0

---

psalm.xml
src/Controller/DefaultController.php
src/Controller/Task/Base.php
src/Controller/Task/Delete.php
src/Controller/Task/GetAll.php
src/Controller/Task/GetOne.php
src/Controller/Task/Search.php
src/Controller/User/Base.php
src/Controller/User/Delete.php
src/Controller/User/Update.php
src/Middleware/Auth.php
src/Repository/NoteRepository.php
src/Repository/UserRepository.php
src/Service/Note/Find.php
src/Service/User/UserService.php

- Update psalm config.
- Improvement detected with psalm.
- Some other minor changes.

Version 1.20.0

---

src/Controller/BaseController.php
src/Controller/DefaultController.php
src/Entity/Note.php
src/Repository/NoteRepository.php
src/Service/Note/Base.php
src/Service/Note/Create.php
src/Service/Note/Find.php
src/Service/Note/Update.php

Version 1.22.0

---

src/Controller/BaseController.php
src/Controller/DefaultController.php
src/Controller/Task/GetAll.php
src/Repository/BaseRepository.php
src/Repository/NoteRepository.php
src/Repository/TaskRepository.php
src/Repository/UserRepository.php
src/Service/Note/Base.php
src/Service/RedisService.php
src/Service/Task/Base.php
src/Service/Task/TaskService.php
src/Service/User/Base.php
tests/integration/BaseTestCase.php
tests/integration/TaskTest.php

- Get Tasks Endpoint: Now allow search tasks by name, description and status.
- Get Tasks Endpoint also allow pagination.
- Some minor changes.

Version 1.23.0

---

src/Controller/DefaultController.php
src/Entity/User.php
src/Repository/UserRepository.php
src/Service/User/Base.php
src/Service/User/UserService.php

Version 1.24.0

---

composer.json
src/App/Routes.php
src/Controller/DefaultController.php
src/Entity/Note.php
src/Entity/Task.php
src/Entity/User.php
src/Repository/TaskRepository.php
src/Service/Task/Base.php
src/Service/Task/TaskService.php

- Add and Use the Task Entity.
- Configure PHPStan to analyze in max level.
- Minor changes.

Version 1.25.0

---

extras/docs/Rest Api Slim PHP.postman_collection.json
extras/docs/endpoints.md
public/docs/swagger.yaml
src/Controller/DefaultController.php

Version 1.26.0

---

README.md
README_SPANISH.md
composer.lock
src/App/Services.php
src/Controller/DefaultController.php
src/Controller/User/Base.php
src/Controller/User/Create.php
src/Controller/User/Delete.php
src/Controller/User/GetAll.php
src/Controller/User/GetOne.php
src/Controller/User/Login.php
src/Controller/User/Update.php
src/Service/User/Create.php
src/Service/User/Delete.php
src/Service/User/Find.php
src/Service/User/Login.php
src/Service/User/Update.php
src/Service/User/UserService.php

Version 2.1.0

---

README.md
README_SPANISH.md
composer.lock
src/Controller/DefaultController.php
src/Repository/TaskRepository.php
src/Service/Task/TaskService.php

Version 2.2.0

---

src/Controller/DefaultController.php
src/Handler/ApiError.php
src/Repository/NoteRepository.php
src/Repository/TaskRepository.php
src/Repository/UserRepository.php
src/Service/Note/Base.php
src/Service/Note/Create.php
src/Service/Note/Update.php
src/Service/Task/Base.php
src/Service/Task/TaskService.php
src/Service/User/Base.php
src/Service/User/Create.php
src/Service/User/Update.php

Version 2.3.0

---

src/Controller/DefaultController.php
src/Repository/BaseRepository.php
src/Repository/NoteRepository.php
src/Repository/UserRepository.php
src/Service/Note/Update.php
src/Service/RedisService.php
src/Service/User/Update.php

- When user update email, validate if that email already exists.
- Fix PHPDoc typo.

Version 2.4.0

---

src/Controller/DefaultController.php
src/Entity/Note.php
src/Entity/Task.php
src/Entity/User.php
src/Service/Note/Base.php
src/Service/Note/Create.php
src/Service/Note/Find.php
src/Service/Note/Update.php
src/Service/Task/Base.php
src/Service/Task/TaskService.php
src/Service/User/Base.php
src/Service/User/Create.php
src/Service/User/Find.php
src/Service/User/Update.php
src/Traits/ArrayOrJsonResponse.php

- Add a trait that allow an entity to response in Array or Json format.
- Use toJson() function in services of User, Task and Notes.

Version 2.5.0

---

.env.example
.scrutinizer.yml
.travis.yml
TROUBLESHOOTING.md
docker-compose.yml
extras/bin/restart-db.php
src/App/App.php
src/App/Dependencies.php
src/App/Settings.php
src/Controller/DefaultController.php

- Add env var DB_PORT, to allow configure the MySQL port.
- Update and rename some environment variables.

Version 2.6.0

---

README.md
README_SPANISH.md
composer.json
composer.lock
src/App/Dependencies.php
src/App/Repositories.php
src/App/Services.php
src/App/Settings.php
src/Controller/BaseController.php
src/Controller/DefaultController.php
src/Entity/Note.php
src/Entity/Task.php
src/Entity/User.php
src/Service/Note/Base.php
src/Service/RedisService.php
src/Service/Task/Base.php
src/Service/User/Base.php
tests/integration/BaseTestCase.php
tests/integration/NoteTest.php
tests/integration/TaskTest.php
tests/integration/UserTest.php

- Run PHP CS Fixer.
- Removed Rector package.
- Added again PHP insights.
- Composer update.
- Fixed 'display error details' value to true/false.
- Add a custom Not Found Handler.

Version 2.9.0

---

docker-compose.yml
extras/bin/restart-db.php
src/Controller/DefaultController.php

- Fixed error when running: **extras/bin/restart-db.php**
- Nginx service depend on PHP.

Version 2.11.0

---

README.md
README_SPANISH.md
composer.json
composer.lock
src/Controller/DefaultController.php

- Require PHP 7.4 or 8.0.
- Composer Update.

Version 2.12.0

---

README.md
README_SPANISH.md
composer.json
composer.lock
extras/docs/Rest Api Slim PHP.postman_collection.json
extras/docs/endpoints.md
public/docs/swagger.yaml
src/Controller/DefaultController.php

- Update pestphp/pest.
- Update and Fix Swagger Documentation.
- Composer update.

Version 2.13.0

---

README.md
README_SPANISH.md
composer.lock
src/App/Dependencies.php
src/Controller/DefaultController.php
src/Exception/NotFound.php

- Create and use a dedicated exception for Route Not Found.
- Composer update.

Version 2.14.0

---

composer.lock
database/database.sql
src/Controller/DefaultController.php
src/Repository/UserRepository.php
src/Service/User/Create.php
src/Service/User/Login.php

- Improve password hashing security using **password_hash** and **password_verify**.
- Salt is validated and generated automatically by PHP functions: password_hash and password_verify.

Version 2.17.0

---

.travis.yml
README.md
README_SPANISH.md
composer.json
composer.lock
src/Controller/DefaultController.php

- Added command: "composer phpinsights", to run PHP Insights :-)

Version 2.18.0

---

extras/bin/restart-db.php
rector.php
src/App/Repositories.php
src/App/Settings.php
src/Controller/BaseController.php
src/Controller/DefaultController.php
src/Controller/Task/Base.php
src/Controller/User/Base.php
src/Repository/BaseRepository.php
src/Repository/TaskRepository.php
src/Repository/UserRepository.php
src/Service/Note/Base.php
src/Service/Note/Create.php
src/Service/Task/TaskService.php
src/Service/User/Create.php
src/Service/User/Update.php

- Resolved some issues detected using PHP Stan & PHP Insights.
- Upgrade RectorConfig (from "ContainerConfigurator").
- Some other minor changes.

Version 2.19.0

---

README.md
README_SPANISH.md
src/App/App.php
src/Controller/DefaultController.php

- In App.php: Replaced "require" with "require_once".

Version 2.20.0

---

phpunit.xml
src/App/Routes.php
src/Controller/DefaultController.php
src/Repository/UserRepository.php
tests/integration/UserTest.php

- Added unit test. To test the login endpoint with an existing user but a wrong password.

Version 2.21.0

---

composer.json
composer.lock
src/Controller/DefaultController.php

- Bump Psalm from version 4.18 to 5.14  
- Fix https://github.com/maurobonfietti/rest-api-slim-php/issues/151

Version 2.22.0

---

README.md
README_SPANISH.md
composer.lock
src/Controller/DefaultController.php

Version 2.23.0

---

.env.example
composer.json
composer.lock
src/Controller/DefaultController.php
src/Middleware/Base.php
src/Service/User/Login.php

- Upgrade to firebase/php-jwt version 6.
- Update APP_DOMAIN to a more generic and secure domain name 😄

Version 2.24
